# Generated by Django 5.1.7 on 2025-03-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatutModel',
            new_name='StatusModel',
        ),
    ]
